spring.application.name=Library

spring.sql.init.platform=devData

logging.level.org.springframework.jdbc=DEBUG

spring.h2.console.enabled=true
spring.datasource.generate-unique-name=false
spring.datasource.name=bookstore

spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
